---
title: "NYC restaurant dashboard"
author: "Jiaqi Li & Leiyu Yue"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(readr)
library(dplyr)
library(tidytext)
```

```{r}
### load data
nyc_inspections <- read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>% 
  filter(grade %in% c("A", "B", "C"),
         boro != "Missing") %>% 
  mutate(boro = str_to_title(boro),
         inspection_num = row_number()) %>%
  select(inspection_num, boro, grade, cuisine_description, violation_description)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
type <- nyc_inspections %>% 
  distinct(cuisine_description) %>% 
  pull()

# selectInput widget

selectInput("cuisine_type", label = h3("Select cuisine type"),
            choices = type, selected = "American")

boros <- nyc_inspections %>% 
  distinct(boro) %>% 
  pull()

# radioButtons widget

radioButtons("boro_choice", label = h3("Select boro"),
             choices = boros, selected = "Manhattan")
```


Row
-----------------------------------------------------------------------

### The 10 most frequently used words in "violation description"

```{r}

inspection_words = nyc_inspections %>% 
  unnest_tokens(word, violation_description)

data(stop_words)

inspection_words = 
  anti_join(inspection_words, stop_words)

renderPlotly({
inspection_words %>% 
    filter(cuisine_description == input$cuisine_type,
           boro == input$boro_choice) %>% 
  count(word, sort = TRUE) %>% 
  head(10) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  plot_ly(x = ~word, y = ~n, type = "bar", color = ~word)
    
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### The percentage of grade A, B, C restaurants in NYC

```{r}
renderPlotly({
  nyc_inspections %>%
    filter(cuisine_description == input$cuisine_type,
           boro == input$boro_choice) %>% 
  group_by(grade) %>%
  summarize(count = n()) %>%
  mutate(percentage = paste(round(count/sum(count), 2)*100, "%")) %>% 
  plot_ly(labels = ~grade, values = ~count) %>%
  add_pie(hole = 0.6) %>%
  layout(showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

### Number of grade A, B, C restaurants for each boro

```{r}
renderPlotly({
  nyc_inspections %>% 
    filter(cuisine_description == input$cuisine_type) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n) %>% 
  plot_ly( x = ~boro, y =~A, type = 'bar', name = 'A') %>% 
  add_trace(y =~B, name = "B") %>%
  add_trace(y =~C, name = "C") %>% 
  layout(yaxis = list(title = 'Count'), barmode = 'stack')
})
```

```{r}
## update on shiny
# rsconnect::deployApp('/Users/jiaqili/Desktop/Data Science_2017Fall/HW/p8105_hw6_jl5025/p8105_hw6_jl5025_problem2')
```

